name: Build CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cc: [ gcc-10, gcc-11, clang-13, clang-14 ]
    env: 
      PREFIX: /usr/local/bin
      CC: ${{ matrix.cc }}

    steps:
    - uses: actions/checkout@v3
    - name: CC ver
      run: ${CC} -v
    - name: make
      run: make
    - name: make install
      run: sudo make install
    - name: ldd
      run: ldd $PREFIX/mdp
    - name: version
      run: $PREFIX/mdp -v

