name: Build CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [ clang-latest, gcc-latest, gcc-10, gcc-11, clang-11, clang-12 ]
    env: 
      PREFIX: /usr/local/bin
      CC: ${{ matrix.cc }}

    steps:
    - uses: actions/checkout@v3
    - name: CC ver
      run: cc -v
    - name: make
      run: make
    - name: make install
      run: sudo make install
    - name: ldd
      run: ldd $PREFIX/mdp
    - name: version
      run: $PREFIX/mdp -v

